// src/gg_chess/web/static/ui/src/gamelist.jsx
// Game list sidebar. Shows recent games ranked by learning value.

function GameList({ games, activeId, onSelect }) {
  return (
    <div className="gl-root">
      <div className="gl-header">
        <div className="gl-title">
          <span className="gl-title-main">Recent games</span>
          <span className="gl-title-sub">ranked by learning value</span>
        </div>
        <button className="gl-sync" title="Sync with chess.com">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="23 4 23 10 17 10" />
            <polyline points="1 20 1 14 7 14" />
            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
          </svg>
        </button>
      </div>

      <div className="gl-user-chip">
        <div className="gl-avatar">jm</div>
        <div className="gl-user-meta">
          <div className="gl-user-name">jmarcus</div>
          <div className="gl-user-stats">1584 · 24 games this month</div>
        </div>
      </div>

      <div className="gl-list">
        {games.map((g) => (
          <GameCard key={g.id} game={g} active={g.id === activeId} onClick={() => onSelect(g.id)} />
        ))}
      </div>

      <style>{`
        .gl-root { display: flex; flex-direction: column; height: 100%; overflow: hidden; }
        .gl-header {
          display: flex; align-items: center; justify-content: space-between;
          padding: 14px 16px 10px;
          border-bottom: 1px solid var(--border);
          flex-shrink: 0;
        }
        .gl-title { display: flex; flex-direction: column; gap: 1px; }
        .gl-title-main {
          font-size: 13px; font-weight: 600; color: var(--text);
          letter-spacing: 0.2px;
        }
        .gl-title-sub {
          font-size: 11px; color: var(--text-dim); font-style: italic;
          font-family: var(--font-serif); letter-spacing: 0.3px;
        }
        .gl-sync {
          background: none;
          border: 1px solid var(--border);
          border-radius: var(--radius-sm);
          color: var(--text-dim);
          width: 28px; height: 28px;
          display: flex; align-items: center; justify-content: center;
          cursor: pointer;
          transition: color 0.15s, background 0.15s, border-color 0.15s;
        }
        .gl-sync:hover {
          color: var(--text); background: var(--surface-2); border-color: var(--border-2);
        }
        .gl-user-chip {
          display: flex; align-items: center; gap: 10px;
          padding: 10px 16px;
          border-bottom: 1px solid var(--border);
          flex-shrink: 0;
        }
        .gl-avatar {
          width: 32px; height: 32px; border-radius: 50%;
          background: var(--accent-muted); color: var(--accent);
          display: flex; align-items: center; justify-content: center;
          font-size: 12px; font-weight: 700; font-family: var(--font-mono);
          border: 1px solid var(--accent-dim);
        }
        .gl-user-meta { flex: 1; min-width: 0; }
        .gl-user-name {
          font-size: 13px; font-weight: 600; color: var(--text);
        }
        .gl-user-stats {
          font-size: 11px; color: var(--text-dim); font-family: var(--font-mono);
        }
        .gl-list { flex: 1; overflow-y: auto; }
      `}</style>
    </div>
  );
}

function GameCard({ game, active, onClick }) {
  const resultChar = game.result === "win" ? "W" : game.result === "loss" ? "L" : "D";
  const resultColor = game.result === "win" ? "var(--accent)"
                   : game.result === "loss" ? "var(--danger)"
                   : "var(--text-dim)";
  const learning = Math.round(game.interest * 100);

  return (
    <button className={`gc ${active ? "active" : ""}`} onClick={onClick}>
      <div className="gc-top">
        <div className="gc-result" style={{ color: resultColor, borderColor: resultColor }}>
          {resultChar}
        </div>
        <div className="gc-info">
          <div className="gc-vs">
            <span className="gc-opp">vs. {game.opponent}</span>
            <span className="gc-rating">{game.oppRating}</span>
          </div>
          <div className="gc-opening">{game.opening}</div>
        </div>
      </div>
      <div className="gc-bottom">
        <div className="gc-meta">
          <span className="gc-date">{shortDate(game.playedAt)}</span>
          <span className="gc-dot">·</span>
          <span className="gc-tc">{game.timeControl}</span>
          <span className="gc-dot">·</span>
          <span className="gc-ply">{Math.ceil(game.ply/2)} moves</span>
        </div>
        <div className="gc-badges">
          {game.errorCount > 0 && (
            <span className="gc-badge err">
              <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/></svg>
              {game.errorCount}
            </span>
          )}
          <LearningPip value={learning} />
          {game.phase === "done" && <span className="gc-badge done">✓</span>}
          {game.phase === "in_progress" && <span className="gc-badge prog">…</span>}
        </div>
      </div>

      <style>{`
        .gc {
          display: block; width: 100%; text-align: left;
          background: none; border: none;
          border-bottom: 1px solid var(--border);
          border-left: 2px solid transparent;
          padding: 12px 16px;
          cursor: pointer; color: inherit; font: inherit;
          transition: background 0.12s, border-left-color 0.12s;
        }
        .gc:hover { background: var(--surface-2); }
        .gc.active { background: var(--accent-muted); border-left-color: var(--accent); }
        .gc-top { display: flex; gap: 10px; align-items: center; margin-bottom: 6px; }
        .gc-result {
          width: 24px; height: 24px; flex-shrink: 0;
          border-radius: 4px; border: 1px solid;
          display: flex; align-items: center; justify-content: center;
          font-size: 12px; font-weight: 700; font-family: var(--font-mono);
        }
        .gc-info { flex: 1; min-width: 0; }
        .gc-vs {
          display: flex; align-items: baseline; gap: 6px;
          font-size: 13px; color: var(--text);
        }
        .gc-opp { font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .gc-rating { font-family: var(--font-mono); font-size: 11px; color: var(--text-dim); }
        .gc-opening {
          font-size: 11px; color: var(--text-muted);
          font-style: italic; font-family: var(--font-serif);
          white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
        }
        .gc-bottom {
          display: flex; justify-content: space-between; align-items: center;
          padding-left: 34px;
        }
        .gc-meta {
          display: flex; align-items: center; gap: 5px;
          font-size: 11px; color: var(--text-dim); font-family: var(--font-mono);
        }
        .gc-dot { opacity: 0.5; }
        .gc-badges { display: flex; align-items: center; gap: 6px; }
        .gc-badge {
          font-size: 10px; font-family: var(--font-mono);
          display: inline-flex; align-items: center; gap: 2px;
          padding: 1px 5px; border-radius: 99px;
        }
        .gc-badge.err { color: var(--warn); background: var(--warn-muted); }
        .gc-badge.done { color: var(--accent); font-size: 11px; }
        .gc-badge.prog { color: var(--warn); font-size: 12px; }
      `}</style>
    </button>
  );
}

function LearningPip({ value }) {
  const bars = 5;
  const filled = Math.max(1, Math.min(bars, Math.round(value / 20)));
  return (
    <span className="pip" title={`Learning value ${value}%`}>
      {Array.from({ length: bars }).map((_, i) => (
        <span key={i} className={`pip-bar ${i < filled ? "on" : ""}`} />
      ))}
      <style>{`
        .pip { display: inline-flex; align-items: flex-end; gap: 1.5px; height: 10px; }
        .pip-bar {
          width: 2px;
          background: var(--border-2);
          border-radius: 1px;
        }
        .pip-bar:nth-child(1) { height: 3px; }
        .pip-bar:nth-child(2) { height: 5px; }
        .pip-bar:nth-child(3) { height: 7px; }
        .pip-bar:nth-child(4) { height: 9px; }
        .pip-bar:nth-child(5) { height: 11px; }
        .pip-bar.on { background: var(--accent); }
      `}</style>
    </span>
  );
}

function shortDate(iso) {
  const d = new Date(iso + "T00:00:00");
  const today = new Date("2026-04-19");
  const diff = Math.round((today - d) / (86400 * 1000));
  if (diff === 0) return "Today";
  if (diff === 1) return "Yesterday";
  if (diff < 7) return `${diff}d ago`;
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

Object.assign(window, { GameList, GameCard, LearningPip, shortDate });

// frontend/src/lib/GameList.svelte
<script>
  import { onMount } from "svelte";
  import { games, currentGame, history, currentIndex, currentAnalysis, chatMessages } from "../stores.js";
  import { Chess } from "chess.js";

  const username = "jumpyfile";
  let loading = false;
  let error = "";

  onMount(() => fetchGames());

  async function fetchGames() {
    loading = true;
    error = "";
    try {
      const res = await fetch(`/api/games?username=${encodeURIComponent(username)}`);
      if (!res.ok) throw new Error("Failed to fetch games");
      games.set(await res.json());
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  async function selectGame(game) {
    const res = await fetch(`/api/game/${game.id}`);
    if (!res.ok) return;
    const data = await res.json();

    const chess = new Chess();
    chess.loadPgn(data.pgn);
    const moves = chess.history({ verbose: true });

    const chess2 = new Chess();
    const hist = [{ fen: chess2.fen(), san: null, uci: null, move_number: 0 }];
    for (const m of moves) {
      chess2.move(m);
      hist.push({ fen: chess2.fen(), san: m.san, uci: m.from + m.to + (m.promotion || ""), move_number: m.color === "w" ? Math.ceil(hist.length / 2) : Math.floor(hist.length / 2) });
    }

    currentGame.set({ ...game, ...data });
    history.set(hist);
    currentIndex.set(0);
    currentAnalysis.set(null);
    chatMessages.set([]);
  }

  function formatDate(d) {
    if (!d) return "";
    return new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
  }

  function initials(name) {
    if (!name || name === "?") return "?";
    return name.slice(0, 2).toUpperCase();
  }

  function resultClass(result) {
    if (!result) return "draw";
    const r = result.toLowerCase();
    if (r === "1-0" || r === "win") return "win";
    if (r === "0-1" || r === "loss") return "loss";
    return "draw";
  }

  function resultLabel(result) {
    if (!result) return "D";
    const r = result.toLowerCase();
    if (r === "1-0" || r === "win") return "W";
    if (r === "0-1" || r === "loss") return "L";
    return "D";
  }
</script>

<div class="game-list">
  <div class="panel-header">
    <span class="panel-title">Recent Games</span>
    {#if $games.length > 0}
      <span class="game-count">{$games.length}</span>
    {/if}
  </div>
  {#if loading}
    <div class="loading-hint">Loading games…</div>
  {/if}

  {#if error}
    <p class="error">{error}</p>
  {/if}

  <ul>
    {#each $games as game (game.id)}
      {@const rc = resultClass(game.result)}
      <li class:active={$currentGame?.id === game.id} on:click={() => selectGame(game)}>
        <div class="game-top">
          <div class="avatars">
            <div class="avatar avatar-you" title={username}>{initials(username)}</div>
            <div class="avatar avatar-opp" title={game.opponent ?? "?"}>{initials(game.opponent ?? "?")}</div>
          </div>
          <div class="game-info">
            <div class="game-vs">
              <span class="player-name">{username || "You"}</span>
              <span class="vs">vs</span>
              <span class="player-name">{game.opponent ?? "?"}</span>
            </div>
          </div>
          <span class="result-chip {rc}">{resultLabel(game.result)}</span>
        </div>
        <div class="game-bottom">
          <span class="game-date">{formatDate(game.played_at)}</span>
          {#if game.time_control}
            <span class="time-control">{game.time_control}</span>
          {/if}
          {#if game.error_count > 0}
            <span class="error-badge">⚠ {game.error_count}</span>
          {/if}
        </div>
      </li>
    {/each}
  </ul>
</div>

<style>
  .game-list {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }
  .panel-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 12px 6px;
    flex-shrink: 0;
  }
  .panel-title {
    font-size: 11px;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: var(--text-dim);
  }
  .game-count {
    font-size: 11px;
    color: var(--text-dim);
    background: var(--surface2);
    border-radius: 10px;
    padding: 1px 7px;
  }
  .loading-hint {
    padding: 4px 12px 8px;
    font-size: 12px;
    color: var(--text-dim);
    flex-shrink: 0;
  }
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
    overflow-y: auto;
    flex: 1;
  }
  li {
    padding: 10px 12px;
    cursor: pointer;
    border-bottom: 1px solid var(--border);
    border-left: 2px solid transparent;
    transition: background 0.12s;
  }
  li:hover { background: var(--surface2); }
  li.active {
    background: var(--accent-muted);
    border-left-color: var(--accent);
  }
  .game-top {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 6px;
  }
  .avatars {
    display: flex;
    flex-shrink: 0;
  }
  .avatar {
    width: 28px;
    height: 28px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 10px;
    font-weight: 600;
    border: 2px solid var(--bg);
  }
  .avatar-you {
    background: #2e4a1c;
    color: var(--accent);
    z-index: 1;
  }
  .avatar-opp {
    background: var(--surface2);
    color: var(--text-muted);
    margin-left: -8px;
  }
  .game-info { flex: 1; min-width: 0; }
  .game-vs {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 12px;
  }
  .player-name {
    color: var(--text-muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 60px;
  }
  .vs { color: var(--text-dim); font-size: 11px; }
  .result-chip {
    flex-shrink: 0;
    width: 22px;
    height: 22px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 700;
  }
  .result-chip.win { background: rgba(129,182,76,0.2); color: var(--accent); }
  .result-chip.loss { background: rgba(192,57,43,0.2); color: #e74c3c; }
  .result-chip.draw { background: var(--surface2); color: var(--text-dim); }
  .game-bottom {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 11px;
  }
  .game-date { color: var(--text-dim); flex: 1; }
  .time-control { color: var(--text-dim); }
  .error-badge { color: #e67e22; font-size: 11px; }
  .error { color: #e74c3c; padding: 8px 12px; font-size: 12px; margin: 0; }
</style>
